_target_: src.models.dysco.DYSCO
detector: ${detector}

multimodal_encoder:
  _target_: src.models.encoders.multimodal.long_clip.LongCLIPEncoder
  model_name: "longclip-B"

interaction_transforms:
  _target_: src.data.components.interaction_transforms.Compose
  transforms:
    - _target_: src.data.components.interaction_transforms.TargetCrop
